---
detectors:
  InstanceVariableAssumption:
    enabled: false
  IrresponsibleModule:
    enabled: false
  NilCheck:
    enabled: false
  TooManyInstanceVariables:
    enabled: false
  TooManyMethods:
    enabled: false
  UtilityFunction:
    enabled: false
